# ============================================
# ??????????? ? PostgreSQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/CatologistNeuralNetworks
spring.datasource.username=postgres
spring.datasource.password=1488
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# Thymeleaf
# ============================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ============================================
# ??????????? ???????
# ============================================
spring.web.resources.static-locations=classpath:/static/

# ============================================
# ??????
# ============================================
server.port=8080